### ISSUE TITLE
Custom tooltip dosen't work Timeline  ver. 0.1.6

### ISSUE THREAD

**Issue by sysmat** [FERNman/angular-google-charts#103]
Tooltip dosen't work in ver. 0.1.6

```html
<google-chart #chart
                width="1200"
                [type]="'Timeline'"
                [data]="data"
                [roles]="roles"
                [columnNames]="['Name', 'Reason', 'Start date', 'End date']"
                [options]="options">
  </google-chart>
```

```typescript
roles: Array<{ role: string, type: string, index?: number, p?: object }> = [
    { role: 'tooltip', type: 'string', index: 4, p: { html: true } }
  ];
...
absences.forEach(abs => {    
      this.data.push([abs.username, abs.reason, dayToStart, dayToEnd, 'custom tooltip']);
    });
..

```

It is displaying default tooltip

**Comment by Parvathijee** [comment]
As per documentation it should be the third parameter in the array of data.

Change the index of tooltip to 2 here instead of 4.
roles: Array<{ role: string, type: string, index?: number, p?: object }> = [
    { role: 'tooltip', type: 'string', index: 2, p: { html: true } }
  ];

and change 
this.data.push([abs.username, abs.reason,  'custom tooltip', dayToStart, dayToEnd]);
