### ISSUE TITLE
Getting "Can't create a Google Chart without data" when trying to use arrayToDataTable

### ISSUE THREAD

**Issue by peterlitvak** [FERNman/angular-google-charts#107]
If I do it like so:
```typescript
...
const chartType = GoogleChartPackagesHelper.getPackageForChartName('ComboChart')
...
private chartData: any
ngOnInit(): void {
  this.loaderService.onReady.subscribe(() => {
    this.loaderService.loadChartPackages([chartType]).subscribe(() => {
      this.chartData = google.visualization.arrayToDataTable([
        [
          'Month',
          'Bolivia',
          'Ecuador',
          'Madagascar',
          'Papua New Guinea',
          'Rwanda',
          'Average',
        ],
        ['2004/05', 165, 938, 522, 998, 450, 614.6],
        ['2005/06', 135, 1120, 599, 1268, 288, 682],
        ['2006/07', 157, 1167, 587, 807, 397, 623],
        ['2007/08', 139, 1110, 615, 968, 215, 609.4],
        ['2008/09', 136, 691, 629, 1026, 366, 569.6],
      ])
    })
  })
}
```

I get this error:
```
app-config.js?db19:79 Error: Can't create a Google Chart without data!
    at GoogleChartComponent.ngOnInit (angular-google-charts.js?3af4:508)
    at checkAndUpdateDirectiveInline (core.js?09c9:22099)
    at checkAndUpdateNodeInline (core.js?09c9:23363)
    at checkAndUpdateNode (core.js?09c9:23325)
    at debugCheckAndUpdateNode (core.js?09c9:23959)
    at debugCheckDirectivesFn (core.js?09c9:23919)
```

**Comment by FERNman** [comment]
In general, you don't need to use this method, except if you are using the `raw-chart`. Can you show me how you wanted to bind the `chartData` to the component?

A bit of background information: The error happens when trying to create a chart without data. In the next version, I'll maybe look into this and change it so it's no longer happening.
For now, it should be possible to fix this by simply using `ngIf` in the template until the chart data is fetched.

**Comment by peterlitvak** [comment]
I was just trying to make sure that I can use google.visialization stuff directly with this component. It is not critical at the moment so I've moved on.

**Comment by crush83** [comment]
I have this same issue. The `google.visualization` library isn't available at the time I'm trying to build my chart data. So, there's a bit of a chicken and egg issue happening. One way I could think to solve it would be to track a `chartPackagesLoaded` boolean on the component that is loading the Google Chart libraries.

For example, at the bottom of your:

    this.loaderService.onReady.subscribe(() => {
       this.loaderService.loadChartPackages([chartType]).subscribe(() => {
          //Your code to create chart data here.
          this.chartPackagesLoaded = true;
       });
    });

Then, in the template:

    <div *ngIf="chartPackagesLoaded">
       <google-chart [data]="myChartData"></google-chart>
    </div>

This would ensure that the chart components don't try to load before your data for them has been created, essentially.

Another idea is to have something higher up in your application architecture pull down the visualization library by just loading the most common chart type, so that it's already loaded by the time your component runs. If you have an application initialization/loading stage on your app, you could potentially do it there. This assumes the rest of your sites components aren't initialized until your site says its ready.
