### ISSUE TITLE
How to create table legend for ComboChart

### ISSUE THREAD

**Issue by svzi** [FERNman/angular-google-charts#128]
Hi there!

First of all, thanks for this awesome plugin @FERNman , I really appreciate it! (y)

I've created a combo chart, but I'm unable to show a legend. The official documentation has the legend as first row in the data array, as shown here: https://developers.google.com/chart/interactive/docs/gallery/combochart

But whenever I insert my legend in that format to the data array, I got the following error message from your plugin: `Data column(s) for axis #0 cannot be of type string`

I'm still unable to figure out a way to show my legend. Could you please point me to the right direction?

Best,
Sven

**Comment by FERNman** [comment]
Hi @svzi,

You should be able to fix this problem by providing the legend using the `columnNames` property in the `GoogleChartComponent`. Just pass in the legend as an array and only provide the "real" data through the `data` property.

This is necessary because the GooglechartComponent internally uses `arrayToDataTable`, which must know if the first row of the provided data is a legend or not. This is only possible by providing the column names explicitly.

I hope this helps!

**Comment by svzi** [comment]
@FERNman Thanks a lot for your quick response. I totally missed the `columnNames` property. I was just using the `columns`, `data` and `options` property. So thank you very much for the heads up! 

Thanks again for the good work!
