### ISSUE TITLE
Dynamic Resize

### ISSUE THREAD

**Issue by iTheBOSSx** [FERNman/angular-google-charts#141]
# Bug Report

## Prerequisites

- [x] I am running the latest version
- [x] I checked the Readme and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] This is related to angular-google-charts and not to Google Charts directly (if it's a Google Charts issue, [their forum](https://groups.google.com/forum/#!forum/google-visualization-api) may help)

## Description

The property dynamicResize is working on Firefox but not on Chrome.

Thank you so much.

## Your environment
<pre><code>
Angular CLI: 8.3.26
Node: 13.13.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.26
@angular-devkit/build-optimizer   0.803.26
@angular-devkit/build-webpack     0.803.26
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cdk                      8.2.3
@angular/cli                      8.3.26
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.3
@ngtools/webpack                  8.3.26
@nguniversal/express-engine       8.2.6
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Comment by FERNman** [comment]
Hi @iTheBOSSx, can you tell me exactly what it is that's not working? Or even better, create a rep

I'm developing on Chrome myself, and for me, it's working perfectly fine.

**Comment by efrenpar** [comment]
I found the same problem, is not working when the chart is loading for the firste tiem, but in firefox it works fine at the beggining.

**Comment by anyeone** [comment]
I put breakpoints in the node_modules version of the angular-google-charts component using the developer tools in Chrome to track this down, as I'm seeing the same issue today.

The ngOnChanges() for the GoogleChartComponent is not firing at all when the browser window is resized.

It fires during the initial loading of the control and as the properties are passed in, but after the load completes if I resize my browser window it doesn't fire.  So whether you have dynamicResize set to true or false is irrelevant because the logic to redraw isn't ever hit. 

So the question is why doesn't resizing the page trigger this?
I'm applying an ngClass to the chart with this style:
  .single-data-yoy-overview-chart{
    background-color: transparent;
    background: none;
    height: 90%;
    width: 90%;
  }
wrapped in a div with this styling:
.single-data-yoy-overview-wrapper{
    display: flex;
    align-content: center;
    align-items: center;
    margin-top: 12px;
    height: calc(100vh - 380px);
    width:  100%;
    flex-wrap: wrap;
  }
  
It's honoring the % sizing during the initial load just fine;  the wrapper changes size properly as the browser changes (I can see this on the Elements tab).

This may be a browser problem, I have the latest Chrome: Version 111.0.5563.64 (Official Build) (arm64) running on MacOS Ventura 13.2.1
