### ISSUE TITLE
How do I achieve this using angular-google-charts

### ISSUE THREAD

**Issue by stefan1st** [FERNman/angular-google-charts#168]
Hello,

I'm struggling to achieve this using angular-google-charts:

```
const timelineChart = new google.visualization.ChartWrapper({
    chartType: 'Timeline',
    containerId: 'chart',
    dataTable: google.visualization.arrayToDataTable([['Name', 'Status', 'Start', 'End']].concat(result).map((row, index) => {
      if (index === 0) {
        return row;
      } else {
        return [
          row[0],
          row[1],
          new Date(row[2]),
          new Date(row[3])
        ];
      }
    })),
    options: {
      timeline: {
        showBarLabels: false
      },
      avoidOverlappingGridLines: true,
      colors: colors
    }
  });
  timelineChart.draw();
```

**This is what I've tried**

 _HTML_ 
 
` <google-chart #containerEl></google-chart>`
 
 _TS:_
 
 ```
 @ViewChild('containerEl', { read: ElementRef })
  private containerEl: ElementRef<HTMLElement>;
  timelineChart: any = {};
  
  
  
    ngOnInit(): void {
        
        this.loaderService.loadChartPackages(this.chartPackage).subscribe(() => {
            // Start creating your chart now
            this.timelineChart = new google.visualization.Timeline(this.containerEl.nativeElement);
          });
	}
 
 
	draw(){
		this.timelineChart = new google.visualization.ChartWrapper({
				chartType: 'Timeline',
				dataTable: google.visualization.arrayToDataTable([['Name', 'Status', 'Start', 'End']].concat(result).map((row, index) => {
				  if (index === 0) {
					return row;
				  } else {
					return [
					  row[0],
					  row[1],
					  new Date(row[2]),
					  new Date(row[3])
					];
				  }
				})),
				options: {
				  timeline: {
					showBarLabels: false
				  },
				  avoidOverlappingGridLines: true,
				  colors: colors
				}
			  });
			  
			this.timelineChart.draw();
	}
```

 ERROR ReferenceError: google is not defined

Can I have a example please?

**Comment by FERNman** [comment]
You definitely should not have to do `new google.visualization.ChartWrapper` by yourself, that's exactly what this library tries to abstract away ;)

In general, I would go through the documentation for the `GoogleChartComponent`. Specifically [`type`](https://github.com/FERNman/angular-google-charts#type), [`options`](https://github.com/FERNman/angular-google-charts#options), [`columns`](https://github.com/FERNman/angular-google-charts#columns) and [`data`](https://github.com/FERNman/angular-google-charts#data) are the important bits in order to get your code to work.

You should provide the column names ("Name", "Status", "Start" and "End" in your case) using the `columns` property. The `data` property should contain the already mapped `result` array.

Let me know if that worked for you!

**Comment by stefan1st** [comment]
It worked, thanks
