### ISSUE TITLE
Getting an undefined value somewhere in the script loading process leading to a 404 error

### ISSUE THREAD

**Issue by adzza24** [FERNman/angular-google-charts#17]
I get a 404 error when the module tries to get the google script by the looks of it:
```
GET https://www.gstatic.com/charts/45.2/js/jsapi_compiled_undefined_module.js
```

Looks like there is a variable merging into the script name there which is `undefined`, but there is no error handling to alert me to what is missing.

Could do with some guidance on what I have done wrong, and an enhancement here could be to check for `undefined` and report it instead of allowing the GET to still fire.

Thanks for you help in advance!

**Comment by adzza24** [comment]
Ok, so the mistake is this:
```
[type]="PieChart" >>> [type]="'PieChart'"
```
So its a stupid mistake on my part, but a check and error handling for `@Input() type` would be an excellent addition :)

**Comment by FERNman** [comment]
This is an Angular error as far as I know and hopefully will be fixed in the future. They had type-checking for inputs already, but since 4.0 it's broken. See [this feature request](https://github.com/angular/angular/issues/24625) for more information.

Therefore I think its an overkill to do type-checking myself as Typescript should do that. Correct me if I'm wrong and it's good practice to do type-checking for inputs manually. For now, I'll close this.

**Comment by adzza24** [comment]
No problem. It's not actually the type that needs to be checked just the existence of the variable which is called `type`. It probable doesn't matter, but I just thought a more descriptive error might be useful here. Great library though dude - thanks for setting this up.
