### ISSUE TITLE
Unable to use map charts

### ISSUE THREAD

**Issue by AndreHermanto** [FERNman/angular-google-charts#203]
Hi, 

I want to load Google Map as a chart. I already got the API key and put it in the root configuration, however it still result in `object is not iterable (cannot read property Symbol(Symbol.iterator))` error.

I created a simple repo to reproduce the issue, just need to fill in your GMap API key on `src/app/app.module.ts`

https://github.com/AndreHermanto/g-chart-map-example

any help would be apprecited.

Thanks

**Comment by FERNman** [comment]
Hi @AndreHermanto,

I think you didn't add the `keys` file to the repo. I guess this was by choice and not by accident but makes it a bit harder to see what the problem is. 
After going over the files real quick, all I can say is that everything looks good to me. Let me know if you figured out what the problem is or if you need more help!

**Comment by AndreHermanto** [comment]
Hi @FERNman,

I added google API key. The error still persist, any help would be appreciated.

Thanks

**Comment by FERNman** [comment]
Hi @AndreHermanto,

I managed to reproduce the issue, thanks for the repository! However, I have no idea as to why this happens. The code is correct in my opinion, and after debugging also the code that's generated by the GoogleChartsComponent, I think the chart is initialized with correct values. 

If you (or someone else) manages to find a solution to that, I'd be happy to hear it!

**Comment by AlmaniaM** [comment]
@FERNman You need to make sure the script loader loads the 'map' package. In the documentation, it shows it here 
![image](https://user-images.githubusercontent.com/8919797/114661508-fd6c3580-9cab-11eb-9754-ed5ff178833e.png). The link to the [documentation](https://developers.google.com/chart/interactive/docs/gallery/map). I debugged the google charts script and it errors out when it tries to create a Google Map object but instead mistakes the JS Map object as being the Google Map since that package isn't loaded.

**Comment by FERNman** [comment]
@AlmaniaM loading the packages should be taken care of by the [`ChartWrapper`](https://developers.google.com/chart/interactive/docs/reference#chartwrapper-class) provided by Google Charts.

**Comment by AlmaniaM** [comment]
@FERNman Not sure if it's a bug or not but while debugging it I noticed that an actual JS Map object was being instantiated instead of a Google Map object when I didn't pass a 'map' package to the `load` function. Maybe the charts library checks for the map by constructor name comparison when determining if it a Google Maps object exists or not. I believe both JS Map and Google Map constructor names would equal to 'Map'. That could be an issue.

**Comment by AlmaniaM** [comment]
@FERNman I did some more digging into this and I believe it's a ChartWrapper bug. You can read more about the issue I posted in the Google Charts Group forum [here](https://groups.google.com/g/google-visualization-api/c/juntkAJpVrs/m/Dc_ID1BBEAAJ). Basically, the ChartWrapper tries to determine if the Google Maps packages is loaded by checking a few namespaces in the `Window` object. If all namespaces fail then it just checks for the name directly in the window object. Example:

1. First, it checks if `Window.google.visualization.Map` is a function?
2. If not, then check if `Window.google.charts.Map` is a function?
3. If not, then check if `Window.gviz.controls.ui.Map` is a function?
4. If not, then check if `Window.Map` is a function?
5. Since `Window.Map` _is_ a function (a JS Map datastructure), then proceed as if the Google Map package is loaded.
Here's an image of the debug session.
![google-chart-wrapper-debug](https://user-images.githubusercontent.com/8919797/114821150-f78e5700-9d74-11eb-9a8f-21e309816f23.png)

I'm sure this type of evaluation works fine for all the different chart types but not so much for the Map constructor.

I'm not exactly sure when they'll fix it so it might be a good idea to put in a special case for the `Map` chart type for now?

**Comment by FERNman** [comment]
Thanks for the detailed investigation @AlmaniaM, really appreciate it! I don't think we need a special case for the map chart, loading the chart packages by default shouldn't do any harm. Maybe the `ChartWrapper` has similar issues for other charts as well, who knows.
