### ISSUE TITLE
How to access control wrapper state value?

### ISSUE THREAD

**Issue by AndreHermanto** [FERNman/angular-google-charts#204]
Hi, 

If I'm using `FilterType.Category` for `control-wrapper`, how do I get the value of the applied filters? Also can I modify the filters programmatically as well?

an example would be great.

Thanks

**Comment by FERNman** [comment]
Hi @AndreHermanto,

You can set the filters by using the input values for the component, `state`. Additionally, you can listen to the `stateChange` event which will be emitted whenever the control wrapper's state changes (I just noticed that `state` doesn't support two-way-binding because the native `statechange` event doesn't emit the new state. Maybe I'll change that behavior so two-way binding actually works).

The current state can be received programatically by calling `myWrapperComponent.controlWrapper.getState()` and can be set using `myWrapperComponent.controlWrapper.setState(state)`.

I hope this answers your question!
