### ISSUE TITLE
I want to center the role annotations on each bar.

### ISSUE THREAD

**Issue by oOBlinkOo** [FERNman/angular-google-charts#212]
Hello im trying to create annotations but i cannot center the text on the middle,I found some references of it:
https://stackoverflow.com/questions/60935887/google-charts-bar-horizontal-move-annotation-position-to-center-of-stacked-chart
and 
https://stackoverflow.com/questions/53001828/google-charts-move-annotation-position-to-center-of-stacked-chart
both are using like mutations classes.

can somebody help me with that?
i have an example:
```  title = 'Population (in millions)';
  type = 'BarChart';

  data = [
    ["2012", 900, 900, 390,390],
    ["2013", 1000,1000, 400,400],
    ["2014", 1170,1170, 440,440],
    ["2015", 1250,1250, 480,480],
    ["2016", 1530,1530, 540,540]
 ];
  columnNames = ['Year', 'Asia',{type: 'string', sourceColumn: 1, role: 'annotation'},'Europe',{type: 'string', sourceColumn: 2, role: 'annotation'}];
  options = {   
    annotations:{
      position:"center"
    },
    hAxis: {
       title: 'Year'
    },
    vAxis:{
       minValue:0
    },
    isStacked:true	  
 };
 ```

![Captura](https://user-images.githubusercontent.com/5222538/110371872-2f3a0e80-8013-11eb-9bfb-63f012ad5a1d.PNG)

**Comment by FERNman** [comment]
Hi @oOBlinkOo,

both of the questions you provide use the [MutationObserver Web API](https://developer.mozilla.org/de/docs/Web/API/MutationObserver), an API that's not specific to Angular Google Charts or even Google Charts. You can access the native `chartWrapper` from the Google-Charts component through its property `chartWrapper` or, even better, the observable `wrapperReady$`. This chart wrapper provides you with everything you need, for example, you can access the chart by calling `getChart()` and the data table with `getDataTable()`.

I'm sure you can figure out the rest by yourself. If you have any issues with the API of this package, please go through the README, everything should be explained there. As this issue is not specific to this repository, I'll close it.
