### ISSUE TITLE
New chart being drawn before old chart disappears

### ISSUE THREAD

**Issue by jkon** [FERNman/angular-google-charts#29]
Not sure if this is an issue with the component or the library, but sometimes when I'm low on memory, and the chart is redrawn due to the data changing, I see the new chart below or next to the old chart before the old chart disappears. Any idea why that would happen and/or how I might fix it or hide it somehow?

**Comment by FERNman** [comment]
Hi @jkon,

I'm pretty sure this is not a problem with this library but rather something that's happening inside the Google Charts library (or maybe angular).
The `GoogleChartsComponent` itself doesn't remove or redraw the chart at all, this is done completely by the Google library. What you could do (not sure if it'll work, but you could try) is clearing the parent DIV of the chart before the data changes. This would probably fix having two charts at the same time.

I assume the problem is that the Google Charts library first renders the new chart and then removes the old one. If I'm wrong, feel free to correct me. I didn't manage to recreate this issue on my PC however.

I'd love to hear what solved it for you!

Good luck,
FERNman
