### ISSUE TITLE
Bar chart is rendered too wide when chart data is a list of nulls and has only one non-null value

### ISSUE THREAD

**Issue by Kayleigh5** [FERNman/angular-google-charts#48]
When the data for the chart has the following structure, the bar chart is rendered too wide:

![screen shot 2019-01-23 at 10 17 31](https://user-images.githubusercontent.com/13117481/51595983-3ddb0f80-1ef8-11e9-9066-023e40470220.png)
<img width="986" alt="screen shot 2019-01-23 at 10 19 28" src="https://user-images.githubusercontent.com/13117481/51596068-69f69080-1ef8-11e9-8526-82a6383cff98.png">

But when I replace one null value with 0, the bar chart is rendered correctly:

![screen shot 2019-01-23 at 10 21 26](https://user-images.githubusercontent.com/13117481/51596213-b772fd80-1ef8-11e9-9adc-85c10143f8cf.png)
<img width="986" alt="screen shot 2019-01-23 at 10 22 40" src="https://user-images.githubusercontent.com/13117481/51596266-da9dad00-1ef8-11e9-8788-cbb52d02e4bf.png">

**Comment by FERNman** [comment]
I've looked into it and can verify that this is an issue. It has nothing to do with how many of the data entries are `null` and how many are `0`, this depends on your screen size and the number of entries.

I can't really tell you what's causing this issue, however, I strongly believe that it's a problem with GoogleCharts itself rather than AngularGoogleCharts.

If you managed to figure it out, I'd love to hear the reason!
