### ISSUE TITLE
How to create a timeline chart using angular-google-charts?

### ISSUE THREAD

**Issue by everyulb** [FERNman/angular-google-charts#49]
I am trying to create a timeline chart in angular.
here is my code

app.component.html

```html
<google-chart [data]="myData" [type]="type"></google-chart>
```

app.component.ts

```typescript
@Component({`
 selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
 title = "CodeSandbox";

  myData = [
    ['Washington', new Date(1789, 3, 30), new Date(1797, 2, 4)],
    ['Adams', new Date(1797, 2, 4), new Date(1801, 2, 4)],
    ['Jefferson', new Date(1801, 2, 4), new Date(1809, 2, 4)]
  ];
  type: string = 'TimelineChart';
}
```

**Comment by FERNman** [comment]
Hi @everyulb, if you haven't figured it out yet: It was the chart type you provided. instead of `TimelineChart`, use `Timeline` and everything will work. 
I think I'll add a section somewhere in the README where one can look up all the Chart Types and their correct names. Thanks for pointing that out!

I'll close that for now, but feel free to reopen if something's still wrong!
