### ISSUE TITLE
google.visualization.DataTable column types

### ISSUE THREAD

**Issue by kamrat11** [FERNman/angular-google-charts#51]
in google charts there is an option to provide column types as part of the data array.
google.visualization.DataTable parses it correctly. this is mainly important where you have dates that can be sent as a string "Date(1,1,2019)";
getDataTable function in goolge-chart-component prevents this.
is there a way to allow this?

**Comment by FERNman** [comment]
Hi @kamrat11, thanks for pointing this out!

Theoretically, it is, of course, possible to allow this. I wasn't able to think of any use case before this issue, so maybe I'll add this in the future.

For now, you should be able to use the `RawChartsComponent` instead of the `GoogleChartsComponent`. This one allows you to pass a data object, just as you would to the Google library normally.

I'd love to hear if this resolves the issue for you!

Best regards, FERNman
