### ISSUE TITLE
Error TypeError: a.X is not a function

### ISSUE THREAD

**Issue by tnaftali** [FERNman/angular-google-charts#60]
Hello, I hope you are well, I've found the library great so far for what I need but I'm having a problem now.
I'm using a chart in which the columns are [Date, number], you can see a screenshot of it here:
![2019-04-21_18-34](https://user-images.githubusercontent.com/8753873/56475899-21059800-6465-11e9-8d0a-2dba02ec0e15.png)
The thing is, I've added a formatter for the dates, so I can change how they look when you hover on a point, and this breaks the chart. This is the data that gets passed to the chart:
![8zjLb1R](https://user-images.githubusercontent.com/8753873/56475903-35499500-6465-11e9-928a-6762140a2e13.png)

But the chart prints this error when I add the formatter:
![uqkEGyn](https://user-images.githubusercontent.com/8753873/56475906-472b3800-6465-11e9-986e-8a1a4bff29e0.png)

I'm guessing it has something to do with it not being able to format the dates correctly?
I've also tried removing the first row of data which are the headers to see if that was it but the error persisted.

This is the html code for the chart:
`<raw-chart [chartData]="rawCharts.Usd.smrCv" [dynamicResize]="true" [formatter]="formatter"></raw-chart>`

If you could help me with this it would be great.

Thanks!

Best regards,
Tobías

**Comment by tnaftali** [comment]
I forgot!
This is the initialization of the formatter:

![2019-04-21_18-54](https://user-images.githubusercontent.com/8753873/56476010-fae0f780-6466-11e9-8a64-e090b99e1c50.png)

**Comment by FERNman** [comment]
Hi @tnaftali 

Thanks a lot for your issue! The detailed description really helped a lot and I was able to figure it out. This was really a bug in the library. It is now fixed in the new release. Sorry that it took so long, but I was busy during the last month doing other things.

A bit of background: What happened is that to format the data, GoogleCharts expects a DataTable object. The `GoogleChartsComponent` creates such an object internally, but the `RawChartComponent` didn't and that's where the problem came from. I hope that it's fixed now. 

If some problems remain, feel free to reopen the issue!

Greetings, FERNman
